export interface DemoProductFixture {
  categorySlug: string;
  description: string;
  imageFileName: string;
  name: string;
  priceMinor: number;
  sku: string;
}

export const DEMO_PRODUCT_FIXTURES: readonly DemoProductFixture[] = [
  {
    categorySlug: "school-supplies",
    description: "A practical blue backpack with multiple compartments for school.",
    imageFileName: "product-blue-backpack.webp",
    name: "Blue school backpack",
    priceMinor: 15_900,
    sku: "KAFIL-DEMO-BLUE-BACKPACK",
  },
  {
    categorySlug: "school-supplies",
    description: "A colorful zip pencil case for pens, pencils, and small supplies.",
    imageFileName: "product-colorful-pencil-case.webp",
    name: "Colorful pencil case",
    priceMinor: 3_900,
    sku: "KAFIL-DEMO-PENCIL-CASE",
  },
  {
    categorySlug: "school-supplies",
    description: "A blue spiral notebook for lessons, notes, and homework.",
    imageFileName: "product-blue-spiral-notebook.webp",
    name: "Blue spiral notebook",
    priceMinor: 1_500,
    sku: "KAFIL-DEMO-SPIRAL-NOTEBOOK",
  },
  {
    categorySlug: "school-supplies",
    description: "A reliable blue ballpoint pen for everyday writing.",
    imageFileName: "product-blue-ballpoint-pen.webp",
    name: "Blue ballpoint pen",
    priceMinor: 500,
    sku: "KAFIL-DEMO-BALLPOINT-PEN",
  },
  {
    categorySlug: "school-supplies",
    description: "A mixed stack of notebooks for several school subjects.",
    imageFileName: "product-stack-of-notebooks.webp",
    name: "School notebook pack",
    priceMinor: 5_900,
    sku: "KAFIL-DEMO-NOTEBOOK-PACK",
  },
  {
    categorySlug: "school-supplies",
    description: "A scientific calculator suitable for secondary-school mathematics.",
    imageFileName: "product-scientific-calculator.webp",
    name: "Scientific calculator",
    priceMinor: 11_900,
    sku: "KAFIL-DEMO-CALCULATOR",
  },
  {
    categorySlug: "personal-care-hygiene",
    description: "A 250 ml pump bottle of Calaine Clean hand sanitizer.",
    imageFileName: "product-calaine-clean-hand-sanitizer.webp",
    name: "Calaine Clean hand sanitizer 250 ml",
    priceMinor: 2_500,
    sku: "KAFIL-DEMO-HAND-SANITIZER",
  },
  {
    categorySlug: "clothing-footwear",
    description: "A simple blue short-sleeve T-shirt for everyday wear.",
    imageFileName: "product-blue-t-shirt.webp",
    name: "Blue T-shirt",
    priceMinor: 6_900,
    sku: "KAFIL-DEMO-BLUE-TSHIRT",
  },
  {
    categorySlug: "clothing-footwear",
    description: "Black Nike-style running shoes with white soles.",
    imageFileName: "product-black-nike-running-shoes.webp",
    name: "Black running shoes",
    priceMinor: 29_900,
    sku: "KAFIL-DEMO-RUNNING-SHOES",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh red tomatoes for salads, sauces, and family meals.",
    imageFileName: "product-tomatoes.webp",
    name: "Fresh tomatoes 1 kg",
    priceMinor: 1_000,
    sku: "KAFIL-DEMO-TOMATOES",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh cucumbers for salads and everyday meals.",
    imageFileName: "product-cucumbers.webp",
    name: "Fresh cucumbers 1 kg",
    priceMinor: 900,
    sku: "KAFIL-DEMO-CUCUMBERS",
  },
  {
    categorySlug: "fresh-produce",
    description: "Everyday potatoes suitable for boiling, roasting, or frying.",
    imageFileName: "product-potatoes.webp",
    name: "Potatoes 1 kg",
    priceMinor: 800,
    sku: "KAFIL-DEMO-POTATOES",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh onions for cooking and seasoning family meals.",
    imageFileName: "product-onions.webp",
    name: "Onions 1 kg",
    priceMinor: 800,
    sku: "KAFIL-DEMO-ONIONS",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh carrots for soups, salads, and cooked dishes.",
    imageFileName: "product-carrots.webp",
    name: "Carrots 1 kg",
    priceMinor: 900,
    sku: "KAFIL-DEMO-CARROTS",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh garlic bulbs for everyday cooking.",
    imageFileName: "product-garlic.webp",
    name: "Garlic 500 g",
    priceMinor: 3_000,
    sku: "KAFIL-DEMO-GARLIC",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh green lettuce for salads and sandwiches.",
    imageFileName: "product-lettuce.webp",
    name: "Fresh lettuce",
    priceMinor: 800,
    sku: "KAFIL-DEMO-LETTUCE",
  },
  {
    categorySlug: "fresh-produce",
    description: "Crisp red apples for snacks and family breakfasts.",
    imageFileName: "product-red-apples.webp",
    name: "Red apples 1 kg",
    priceMinor: 1_800,
    sku: "KAFIL-DEMO-APPLES",
  },
  {
    categorySlug: "fresh-produce",
    description: "Ripe bananas for snacks, breakfasts, and desserts.",
    imageFileName: "product-bananas.webp",
    name: "Bananas 1 kg",
    priceMinor: 1_600,
    sku: "KAFIL-DEMO-BANANAS",
  },
  {
    categorySlug: "fresh-produce",
    description: "Fresh oranges for eating or preparing juice.",
    imageFileName: "product-oranges.webp",
    name: "Oranges 1 kg",
    priceMinor: 1_200,
    sku: "KAFIL-DEMO-ORANGES",
  },
  {
    categorySlug: "dairy-products",
    description: "Gebell Jebli Original fresh cheese for breakfast or sandwiches.",
    imageFileName: "product-gebell-jebli-original-cheese.webp",
    name: "Gebell Jebli Original cheese",
    priceMinor: 2_200,
    sku: "KAFIL-DEMO-JEBLI-CHEESE",
  },
  {
    categorySlug: "deli-processed-meats",
    description: "A family pack of Sir Packal pepperoni for pizzas and sandwiches.",
    imageFileName: "product-sir-packal-pepperoni.webp",
    name: "Sir Packal pepperoni pack",
    priceMinor: 4_900,
    sku: "KAFIL-DEMO-PEPPERONI",
  },
  {
    categorySlug: "baby-products",
    description: "A jumbo pack of Dalaa Baby Comfort size-four disposable diapers.",
    imageFileName: "product-dalaa-baby-comfort-diapers-size-4.webp",
    name: "Dalaa Baby Comfort diapers size 4",
    priceMinor: 10_900,
    sku: "KAFIL-DEMO-DALAA-DIAPERS",
  },
  {
    categorySlug: "meat-poultry",
    description: "A large tray of fresh brown eggs for family meals and baking.",
    imageFileName: "product-tray-of-brown-eggs.webp",
    name: "Brown eggs tray",
    priceMinor: 4_500,
    sku: "KAFIL-DEMO-EGGS",
  },
  {
    categorySlug: "cleaning-supplies",
    description: "Maxis Maison lavender household cleaner for floors and surfaces.",
    imageFileName: "product-maxis-maison-lavender-cleaner.webp",
    name: "Maxis Maison lavender cleaner",
    priceMinor: 2_500,
    sku: "KAFIL-DEMO-MAXIS-CLEANER",
  },
  {
    categorySlug: "dairy-products",
    description: "A four-pack of Chergui Finesse pineapple yogurt.",
    imageFileName: "product-chergui-finesse-pineapple-yogurt.webp",
    name: "Chergui Finesse pineapple yogurt 4-pack",
    priceMinor: 1_800,
    sku: "KAFIL-DEMO-PINEAPPLE-YOGURT",
  },
  {
    categorySlug: "baby-products",
    description: "A 58-pack of Dodot Sensitive size-two disposable diapers.",
    imageFileName: "product-dodot-sensitive-diapers-size-2-58-pack.webp",
    name: "Dodot Sensitive diapers size 2, 58-pack",
    priceMinor: 14_900,
    sku: "KAFIL-DEMO-DODOT-DIAPERS",
  },
  {
    categorySlug: "beverages",
    description: "A large bottle of Ain Atlas natural mineral water.",
    imageFileName: "product-ain-atlas-natural-mineral-water.webp",
    name: "Ain Atlas natural mineral water",
    priceMinor: 1_400,
    sku: "KAFIL-DEMO-AIN-ATLAS-WATER",
  },
  {
    categorySlug: "deli-processed-meats",
    description: "Saila Dindy spicy poultry sausage for sandwiches and quick meals.",
    imageFileName: "product-saila-dindy-kasher-piquati-sausage.webp",
    name: "Saila Dindy Kasher Piquati sausage",
    priceMinor: 3_900,
    sku: "KAFIL-DEMO-SAILA-SAUSAGE",
  },
  {
    categorySlug: "beverages",
    description: "A bottle of Hawai pineapple-flavored soft drink.",
    imageFileName: "product-hawai-pineapple-soda.webp",
    name: "Hawai pineapple soda",
    priceMinor: 1_200,
    sku: "KAFIL-DEMO-HAWAI-PINEAPPLE",
  },
] as const;

const DEMO_PRODUCT_IMAGE_NAMES = new Set(
  DEMO_PRODUCT_FIXTURES.map((fixture) => fixture.imageFileName.toLowerCase()),
);

export function isDemoProductSeedImageName(fileName: string) {
  return DEMO_PRODUCT_IMAGE_NAMES.has(fileName.toLowerCase());
}

export const LEGACY_DEMO_PRODUCT_SKUS = [
  "KAFIL-DEMO-PRODUCE",
  "KAFIL-DEMO-CHICKEN",
  "KAFIL-DEMO-SARDINES",
  "KAFIL-DEMO-MORTADELLA",
  "KAFIL-DEMO-BREAD",
  "KAFIL-DEMO-DAIRY",
  "KAFIL-DEMO-WATER",
  "KAFIL-DEMO-DIAPERS",
  "KAFIL-DEMO-HYGIENE",
  "KAFIL-DEMO-CLEANING",
  "KAFIL-DEMO-JACKET",
  "KAFIL-DEMO-SCHOOL",
  "KAFIL-DEMO-BLOCKS",
  "KAFIL-DEMO-COOKWARE",
  "KAFIL-DEMO-LEDS",
  "KAFIL-DEMO-TOOLS",
  "KAFIL-DEMO-TABLET",
  "KAFIL-DEMO-CATFOOD",
] as const;

export const DEMO_ORDER_PRODUCT_SKUS = [
  "KAFIL-DEMO-TOMATOES",
  "KAFIL-DEMO-POTATOES",
  "KAFIL-DEMO-EGGS",
  "KAFIL-DEMO-JEBLI-CHEESE",
  "KAFIL-DEMO-AIN-ATLAS-WATER",
  "KAFIL-DEMO-NOTEBOOK-PACK",
] as const;
